-- SQL script to add basic user access module tables and seed lookup values
-- Run this against your Claims database

CREATE TABLE [UserRoles]
(
    RoleId BIGINT IDENTITY(1,1) PRIMARY KEY,
    RoleName NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000) NULL
);

CREATE TABLE [AssignmentGroups]
(
    GroupId BIGINT IDENTITY(1,1) PRIMARY KEY,
    GroupCode NVARCHAR(100) NOT NULL,
    GroupName NVARCHAR(200) NOT NULL,
    Description NVARCHAR(1000) NULL
);

CREATE TABLE [Users]
(
    UserId BIGINT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(200) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(1000) NOT NULL,
    FullName NVARCHAR(300) NULL,
    Email NVARCHAR(300) NULL,
    Telephone NVARCHAR(50) NULL,
    Extension NVARCHAR(50) NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT('Active'), -- Active/Disabled
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NULL,
    AssignmentGroupId BIGINT NULL,
    RoleId BIGINT NULL,
    SupervisorUserId BIGINT NULL,
    ExpenseReserve DECIMAL(18,2) NULL,
    IndemnityReserve DECIMAL(18,2) NULL,
    ExpensePayment DECIMAL(18,2) NULL,
    IndemnityPayment DECIMAL(18,2) NULL,
    CreatedBy NVARCHAR(200) NULL,
    CreatedOn DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Users_AssignmentGroup FOREIGN KEY(AssignmentGroupId) REFERENCES AssignmentGroups(GroupId),
    CONSTRAINT FK_Users_Role FOREIGN KEY(RoleId) REFERENCES UserRoles(RoleId),
    CONSTRAINT FK_Users_Supervisor FOREIGN KEY(SupervisorUserId) REFERENCES Users(UserId)
);

-- Indexes
CREATE INDEX IX_Users_Username ON Users(Username);

-- Seed common roles
INSERT INTO UserRoles (RoleName, Description) VALUES
('Adjuster', 'Field adjuster'),
('Supervisor', 'Team supervisor'),
('Manager', 'Claims manager'),
('Claims Payment', 'Claims payment user'),
('Inquiry', 'Inquiry role'),
('Subrogation Respondent Adjuster', 'Subrogation respondent'),
('Subrogation Adjuster', 'Subrogation adjuster');

-- Seed assignment groups (example groups from specification)
INSERT INTO AssignmentGroups (GroupCode, GroupName, Description) VALUES
('GroupA','Group A - BI Adjuster','BI adjuster group A'),
('GroupB','Group B - BI Adjuster','BI adjuster group B'),
('GroupC','Group C - BI Adjuster','BI adjuster group C'),
('GroupD','Group D - PD Adjuster','PD adjuster group D'),
('GroupE','Group E - PD Adjuster','PD adjuster group E'),
('GroupF','Group F - PD Adjuster','PD adjuster group F'),
('GroupG','Group G - PIP Adjuster','PIP adjuster group G'),
('GroupH','Group H - PIP Adjuster','PIP adjuster group H'),
('GroupI','Group I - PIP Adjuster','PIP adjuster group I');

-- Example: create an admin user (password should be replaced after deployment)
-- PasswordHash should be generated by the application; the following is placeholder text.
INSERT INTO Users (Username, PasswordHash, FullName, Email, Status, StartDate, CreatedBy)
VALUES ('admin', 'REPLACE_WITH_HASH', 'System Administrator', 'admin@example.com', 'Active', SYSUTCDATETIME(), 'system');

GO
